services:
  - type: web
    name: fake-news-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    region: singapore
    branch: main
    repo: https://github.com/Code-Ph0enix/Fake_News_Detection 
    rootDir: code/backend
